# -*- coding: utf-8 -*-
"""SE LAB TASK-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jxwzvDGd6YLSfYy23bRGuEE0PUbSOXWW

**1. SHORTEST JOB** **FIRST**

A) SJF – Hard-coded values
"""

bt = [5, 3, 8]
bt.sort()

print("Process Order (SJF):", bt)

"""B) SJF – Keyboard Input"""

n = int(input("Enter number of processes: "))
bt = []

for i in range(n):
    bt.append(int(input(f"Enter burst time for P{i+1}: ")))

bt.sort()
print("Process Order (SJF):", bt)

"""C) SJF – Read from File (Single Input Set)"""

with open("sjf_single.txt", "w") as f:
    f.write("5")

with open("sjf_single.txt", "r") as f:
    bt = int(f.read())

print("Single Burst Time:", bt)

"""D) SJF – Read from File (Multiple Input Sets)"""

with open("sjf_multiple.txt", "w") as f:
    f.write("6 2 4")

with open("sjf_multiple.txt", "r") as f:
    bt = list(map(int, f.read().split()))

bt.sort()
print("SJF Order from file:", bt)

"""**2. ROUND ROBIN SCHEDULING**

A) Round Robin – Hard-coded values
"""

burst_time = [5, 4]
time_quantum = 2
print("Burst Time:", burst_time)
print("Time Quantum:", time_quantum)

"""B) Round Robin – Keyboard Input"""

n = int(input("Enter number of processes: "))
bt = []

for i in range(n):
    bt.append(int(input("Enter burst time: ")))

tq = int(input("Enter time quantum: "))
print("BT:", bt, "TQ:", tq)

"""C) Round Robin – Read from File (Single Input Set)"""

with open("rr_single.txt", "w") as f:
    f.write("3")

with open("rr_single.txt", "r") as f:
    tq = int(f.read())

print("Time Quantum from file:", tq)

"""D) Round Robin – Read from File (Multiple Input Sets)"""

with open("rr_multiple.txt", "w") as f:
    f.write("5 4 3")

with open("rr_multiple.txt", "r") as f:
    bt = list(map(int, f.read().split()))

print("Burst Times from file:", bt)

"""**3. PRODUCER–CONSUMER** **PROBLEM**

A) Producer–Consumer – Hard-coded
"""

buffer_size = 5
items = 0

items += 1
print("Produced item:", items)

"""B) Producer–Consumer – Keyboard Input"""

choice = int(input("1. Produce  2. Consume: "))

if choice == 1:
    print("Item Produced")
else:
    print("Item Consumed")

"""C) Producer–Consumer – Read from File (Single Input)"""

with open("pc_single.txt", "w") as f:
    f.write("3")

with open("pc_single.txt", "r") as f:
    items = int(f.read())

print("Items in buffer:", items)

"""D) Producer–Consumer – Read from File (Multiple Inputs)"""

with open("pc_multiple.txt", "w") as f:
    f.write("produce produce consume")

with open("pc_multiple.txt", "r") as f:
    actions = f.read().split()

items = 0
for action in actions:
    if action == "produce":
        items += 1
    elif action == "consume" and items > 0:
        items -= 1

print("Final items in buffer:", items)